// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJR8iLE8kYhaKp8rltQ04dzBkrRhV9QUc',
    appId: '1:842000705656:web:729aeaa200abd49f4ae58d',
    messagingSenderId: '842000705656',
    projectId: 'starter-project-a3191',
    authDomain: 'starter-project-a3191.firebaseapp.com',
    storageBucket: 'starter-project-a3191.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkuv7uaSW87sbaVcgCq_UT7aSTZh6XQ1A',
    appId: '1:842000705656:android:36dbe5071c89cb3f4ae58d',
    messagingSenderId: '842000705656',
    projectId: 'starter-project-a3191',
    storageBucket: 'starter-project-a3191.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJR8iLE8kYhaKp8rltQ04dzBkrRhV9QUc',
    appId: '1:842000705656:web:2dcdf162109088e24ae58d',
    messagingSenderId: '842000705656',
    projectId: 'starter-project-a3191',
    authDomain: 'starter-project-a3191.firebaseapp.com',
    storageBucket: 'starter-project-a3191.firebasestorage.app',
  );
}
